const TEST_COOKIE = "testcookie";
const TEST_COOKIE_VALUE = "valid";
const TEST_TEXT_PATTERN = "abcdefghijklmnopqrstuvwxyz0123456789";
const TEST_TEXT_REPEAT_COUNT = 1000;
const BYTE_PATTERN = "gtr-cf-test-origin\n";
const BYTE_CONTENT_TYPE = "application/octet-stream";
const TEXT_CONTENT_TYPE = "text/plain; charset=utf-8";
const MAX_GENERATED_SIZE = 1024 * 1024 * 1024 * 1024;
const STREAM_CHUNK_SIZE = 64 * 1024;

const textEncoder = new TextEncoder();
const testText = TEST_TEXT_PATTERN.repeat(TEST_TEXT_REPEAT_COUNT);
const testTextBytes = textEncoder.encode(testText);
const bytePatternBytes = textEncoder.encode(BYTE_PATTERN);

interface RangeSpec {
  start: number;
  end: number;
  partial: boolean;
}

function html(body: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: {
      "Content-Type": "text/html; charset=utf-8"
    }
  });
}

function text(body: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: {
      "Content-Type": TEXT_CONTENT_TYPE
    }
  });
}

function index(): Response {
  return html(`<!doctype html>
<html>
  <head>
    <title>GTR CF Test Origin</title>
  </head>
  <body>
    <h1>GTR CF Test Origin</h1>
    <ul>
      <li><a href="/setup.html">Cookie setup</a></li>
      <li><a href="/download/test.txt">Cookie-protected test file</a></li>
      <li><a href="/download-no-cookie/test.txt">No-cookie test file</a></li>
      <li><a href="/download-gtr-cookie-auth/test.txt">GTR cookie auth test file</a></li>
      <li><a href="/bytes/1048576">1 MiB generated bytes</a></li>
      <li><a href="/meta/1048576">1 MiB metadata</a></li>
    </ul>
  </body>
</html>`);
}

function setupPage(): Response {
  return html(`<!doctype html>
<html>
  <head>
    <title>GTR CF Test Origin Cookie Setup</title>
  </head>
  <body>
    <h1>Cookie Setup</h1>
    <p><a href="/">Home</a></p>
    <p><a href="/download/test.txt">Cookie-protected test file</a></p>
    <button onclick="setCookie()">Set Cookie</button>
    <button onclick="clearCookie()">Clear Cookie</button>
    <script>
      function setCookie() {
        document.cookie = "${TEST_COOKIE}=${TEST_COOKIE_VALUE}; path=/; SameSite=Lax";
        alert("Cookie set");
      }
      function clearCookie() {
        document.cookie = "${TEST_COOKIE}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT";
        alert("Cookie cleared");
      }
    </script>
  </body>
</html>`);
}

function getCookieValue(
  header: string | null,
  name: string
): string | undefined {
  if (!header) {
    return undefined;
  }

  for (const part of header.split(";")) {
    const [cookieName, ...valueParts] = part.trim().split("=");
    if (cookieName === name) {
      return valueParts.join("=");
    }
  }

  return undefined;
}

function containsValidTestCookie(payload: string | null): boolean {
  return getCookieValue(payload, TEST_COOKIE) === TEST_COOKIE_VALUE;
}

function hasValidCookie(request: Request): boolean {
  return containsValidTestCookie(request.headers.get("Cookie"));
}

function hasValidGtrCookieAuth(request: Request): boolean {
  if (hasValidCookie(request)) {
    return true;
  }

  const authorization = request.headers.get("Authorization");
  if (!authorization) {
    return false;
  }

  const authMatch = /^(\S+)\s+(.+)$/.exec(authorization);
  if (!authMatch) {
    return false;
  }

  const [, scheme, payload] = authMatch;
  if (!payload || !["GtrCookie", "Gtr2Cookie"].includes(scheme)) {
    return false;
  }

  return containsValidTestCookie(payload);
}

function parseGeneratedSize(value: string | undefined): number | undefined {
  if (!value || !/^\d+$/.test(value)) {
    return undefined;
  }

  const size = Number(value);
  if (!Number.isSafeInteger(size) || size > MAX_GENERATED_SIZE) {
    return undefined;
  }

  return size;
}

function parseRange(
  rangeHeader: string | null,
  size: number
): RangeSpec | Response {
  if (!rangeHeader) {
    return {
      start: 0,
      end: Math.max(0, size - 1),
      partial: false
    };
  }

  const match = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader);
  if (!match) {
    return text("Invalid Range header\n", 400);
  }

  const [, rawStart, rawEnd] = match;
  if (rawStart === "" && rawEnd === "") {
    return text("Invalid Range header\n", 400);
  }

  if (size === 0) {
    return text("Requested range not satisfiable\n", 416);
  }

  let start: number;
  let end: number;

  if (rawStart === "") {
    const suffixLength = Number(rawEnd);
    if (!Number.isSafeInteger(suffixLength) || suffixLength <= 0) {
      return text("Invalid Range header\n", 400);
    }
    start = Math.max(0, size - suffixLength);
    end = size - 1;
  } else {
    start = Number(rawStart);
    end = rawEnd === "" ? size - 1 : Number(rawEnd);
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end)) {
      return text("Invalid Range header\n", 400);
    }
    end = Math.min(end, size - 1);
  }

  if (start < 0 || start > end || start >= size) {
    return text("Requested range not satisfiable\n", 416);
  }

  return {
    start,
    end,
    partial: true
  };
}

function generatedByteAt(offset: number): number {
  return bytePatternBytes[offset % bytePatternBytes.length];
}

function generatedBytes(start: number, length: number): Uint8Array {
  const bytes = new Uint8Array(length);
  for (let i = 0; i < length; i++) {
    bytes[i] = generatedByteAt(start + i);
  }
  return bytes;
}

function generatedByteStream(
  start: number,
  end: number
): ReadableStream<Uint8Array> {
  let offset = start;

  return new ReadableStream<Uint8Array>({
    pull(controller) {
      if (offset > end) {
        controller.close();
        return;
      }

      const length = Math.min(STREAM_CHUNK_SIZE, end - offset + 1);
      controller.enqueue(generatedBytes(offset, length));
      offset += length;
    }
  });
}

function serveBytes(
  request: Request,
  size: number,
  bodyFactory: (start: number, end: number) => BodyInit | null,
  contentType: string,
  fileName: string
): Response {
  const range = parseRange(request.headers.get("Range"), size);
  if (range instanceof Response) {
    return range;
  }

  const contentLength = size === 0 ? 0 : range.end - range.start + 1;
  const headers = new Headers({
    "Accept-Ranges": "bytes",
    "Content-Disposition": `attachment; filename=${fileName}`,
    "Content-Length": String(contentLength),
    "Content-Type": contentType
  });

  if (range.partial) {
    headers.set("Content-Range", `bytes ${range.start}-${range.end}/${size}`);
  }

  const body =
    request.method === "HEAD" || size === 0
      ? null
      : bodyFactory(range.start, range.end);

  return new Response(body, {
    status: range.partial ? 206 : 200,
    headers
  });
}

function serveTextFixture(request: Request): Response {
  return serveBytes(
    request,
    testTextBytes.length,
    (start, end) => testTextBytes.slice(start, end + 1),
    TEXT_CONTENT_TYPE,
    "test.txt"
  );
}

function serveGeneratedBytes(request: Request, size: number): Response {
  return serveBytes(
    request,
    size,
    (start, end) => generatedByteStream(start, end),
    BYTE_CONTENT_TYPE,
    `bytes-${size}.bin`
  );
}

function redirectToSetup(url: URL): Response {
  return new Response(null, {
    status: 302,
    headers: {
      Location: new URL("/setup.html", url).toString()
    }
  });
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function hex(bytes: Uint8Array): string {
  return [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function metadata(size: number): Promise<Response> {
  const sampleLength = Math.min(size, 64);
  const hashLength = Math.min(size, 64 * 1024);
  const sample = generatedBytes(0, sampleLength);
  const hashSample = generatedBytes(0, hashLength);

  return Response.json({
    size,
    contentType: BYTE_CONTENT_TYPE,
    pattern: BYTE_PATTERN,
    sampleLength,
    sampleHex: hex(sample),
    sha256FirstBytesLength: hashLength,
    sha256FirstBytesHex: await sha256Hex(hashSample)
  });
}

async function route(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const method = request.method;

  if (!["GET", "HEAD"].includes(method)) {
    return text("Method not allowed\n", 405);
  }

  if (url.pathname === "/") {
    return method === "HEAD" ? new Response(null, { status: 200 }) : index();
  }

  if (url.pathname === "/setup.html") {
    return method === "HEAD"
      ? new Response(null, { status: 200 })
      : setupPage();
  }

  if (url.pathname === "/download/test.txt") {
    return hasValidCookie(request)
      ? serveTextFixture(request)
      : redirectToSetup(url);
  }

  if (url.pathname === "/download-no-cookie/test.txt") {
    return serveTextFixture(request);
  }

  if (url.pathname === "/download-gtr-cookie-auth/test.txt") {
    if (!hasValidGtrCookieAuth(request)) {
      return text("Cookie or GTR cookie authorization required\n", 401);
    }
    return serveTextFixture(request);
  }

  const bytesMatch = /^\/bytes\/(\d+)$/.exec(url.pathname);
  if (bytesMatch) {
    const size = parseGeneratedSize(bytesMatch[1]);
    if (size === undefined) {
      return text("Invalid generated size\n", 400);
    }
    return serveGeneratedBytes(request, size);
  }

  const metaMatch = /^\/meta\/(\d+)$/.exec(url.pathname);
  if (metaMatch) {
    if (method === "HEAD") {
      return new Response(null, { status: 200 });
    }
    const size = parseGeneratedSize(metaMatch[1]);
    if (size === undefined) {
      return text("Invalid generated size\n", 400);
    }
    return metadata(size);
  }

  return text("Not found\n", 404);
}

export default {
  fetch(request) {
    return route(request);
  }
} satisfies ExportedHandler;
