import { describe, expect, test } from "vitest";
import worker from "../src/index";

function request(path: string, init?: RequestInit): Promise<Response> {
  return worker.fetch(
    new Request(`https://gtr-cf-test-origin.test${path}`, init) as never
  );
}

async function bodyBytes(response: Response): Promise<Uint8Array> {
  return new Uint8Array(await response.arrayBuffer());
}

describe("gtr-cf-test-origin", () => {
  test("serves an index", async () => {
    const response = await request("/");

    expect(response.status).toBe(200);
    expect(await response.text()).toContain("GTR CF Test Origin");
  });

  test("redirects cookie-protected downloads without a valid cookie", async () => {
    const response = await request("/download/test.txt", {
      redirect: "manual"
    });

    expect(response.status).toBe(302);
    expect(response.headers.get("Location")).toBe(
      "https://gtr-cf-test-origin.test/setup.html"
    );
  });

  test("serves cookie-protected downloads with a valid cookie", async () => {
    const response = await request("/download/test.txt", {
      headers: {
        Cookie: "other=value; testcookie=valid"
      }
    });

    expect(response.status).toBe(200);
    expect(response.headers.get("Accept-Ranges")).toBe("bytes");
    expect(response.headers.get("Content-Length")).toBe("36000");
    expect((await response.text()).length).toBe(36000);
  });

  test("serves no-cookie downloads for GET and HEAD", async () => {
    const getResponse = await request("/download-no-cookie/test.txt");
    const headResponse = await request("/download-no-cookie/test.txt", {
      method: "HEAD"
    });

    expect(getResponse.status).toBe(200);
    expect(headResponse.status).toBe(200);
    expect(headResponse.headers.get("Content-Length")).toBe("36000");
    expect(await headResponse.text()).toBe("");
  });

  test("rejects invalid GTR cookie auth payloads", async () => {
    const response = await request("/download-gtr-cookie-auth/test.txt", {
      headers: {
        Authorization: "GtrCookie testcookie=invalid"
      }
    });

    expect(response.status).toBe(401);
  });

  test("accepts valid GTR cookie auth payloads", async () => {
    const response = await request("/download-gtr-cookie-auth/test.txt", {
      headers: {
        Authorization: "GtrCookie other=value; testcookie=valid"
      }
    });

    expect(response.status).toBe(200);
    expect((await response.text()).length).toBe(36000);
  });

  test("serves generated bytes", async () => {
    const response = await request("/bytes/64");
    const bytes = await bodyBytes(response);

    expect(response.status).toBe(200);
    expect(response.headers.get("Content-Length")).toBe("64");
    expect(new TextDecoder().decode(bytes.slice(0, 18))).toBe(
      "gtr-cf-test-origin"
    );
  });

  test("supports bounded byte ranges", async () => {
    const response = await request("/bytes/1024", {
      headers: {
        Range: "bytes=10-19"
      }
    });
    const bytes = await bodyBytes(response);

    expect(response.status).toBe(206);
    expect(response.headers.get("Content-Range")).toBe("bytes 10-19/1024");
    expect(response.headers.get("Content-Length")).toBe("10");
    expect(bytes.length).toBe(10);
  });

  test("supports open-ended and suffix byte ranges", async () => {
    const openEnded = await request("/bytes/1024", {
      headers: {
        Range: "bytes=1000-"
      }
    });
    const suffix = await request("/bytes/1024", {
      headers: {
        Range: "bytes=-24"
      }
    });

    expect(openEnded.status).toBe(206);
    expect(openEnded.headers.get("Content-Range")).toBe("bytes 1000-1023/1024");
    expect((await bodyBytes(openEnded)).length).toBe(24);

    expect(suffix.status).toBe(206);
    expect(suffix.headers.get("Content-Range")).toBe("bytes 1000-1023/1024");
    expect((await bodyBytes(suffix)).length).toBe(24);
  });

  test("rejects invalid ranges", async () => {
    const malformed = await request("/bytes/1024", {
      headers: {
        Range: "not-a-range"
      }
    });
    const unsatisfiable = await request("/bytes/1024", {
      headers: {
        Range: "bytes=2000-3000"
      }
    });

    expect(malformed.status).toBe(400);
    expect(unsatisfiable.status).toBe(416);
  });

  test("serves metadata for generated bytes", async () => {
    const response = await request("/meta/128");
    const json = await response.json<{
      size: number;
      pattern: string;
      sampleLength: number;
      sampleHex: string;
      sha256FirstBytesLength: number;
      sha256FirstBytesHex: string;
    }>();

    expect(response.status).toBe(200);
    expect(json.size).toBe(128);
    expect(json.pattern).toBe("gtr-cf-test-origin\n");
    expect(json.sampleLength).toBe(64);
    expect(json.sampleHex.length).toBe(128);
    expect(json.sha256FirstBytesLength).toBe(128);
    expect(json.sha256FirstBytesHex).toMatch(/^[0-9a-f]{64}$/);
  });
});
